= Calendula for France

This project contains a script used to transform the french medicine database into a set of SQL statements able to fill a calendula instance with french medicines.

It is built in conjunction with a Calendula `PrescriptionDBMgr` that will be built as soon as this transformer works.

## Getting Started

Just run docker-compose up in project root directory to spin a groovy container that will get the data from public health website

### Prerequisites

You should have docker and docker-compose installed.

## Mapping HAS database to calendula format

I will try to explain how I choose to map french medicine database to calendula format. 
For each file provided in french medicine database, I will give for each field how I plan to map it to calendula.
Information for field usage is obtained from http://base-donnees-publique.medicaments.gouv.fr/docs/Contenu_et_format_des_fichiers_telechargeables_dans_la_BDM_v1.pdf

[NOTE]
----
According to calendula issue https://github.com/citiususc/calendula/issues/103#issuecomment-434270205[#103],
there is a `_id` field in each table, wich is used by http://ormlite.com/[ORMLite].
As this script is mainly a insert into generator, it does not need tha value, which will be left empty.
----

### CIS_bdpm.txt

According to documentation, this is the master file, containing essential informations

* _Code CIS (Code Identifiant de Spécialité)_ mapped to `Prescription#code`
* _Dénomination du médicament_ mapped to `Prescription#name`. **BEWARE** The denomination contains far more than name.
As a consequence, a part of its name will be used to generate HomogenousGroup.
* _Forme pharmaceutique_  mapped to `Prescription#presentationForm`
* _Voies d'administration (avec un séparateur « ; » entre chaque valeur quand il y en a plusieurs)_ **unmapped**
* _Statut administratif de l’autorisation de mise sur le marché (AMM)_ **unmapped**
* _Type de procédure d'autorisation de mise sur le marché (AMM)_ **unmapped**
* _Etat de commercialisation_ **unmapped**
* _Date d’AMM (format JJ/MM/AAAA)_ **unmapped**
* _StatutBdm : valeurs possibles : « Alerte » (icône rouge) ou « Warning disponibilité » (icône grise)_ **unmapped**
* _Numéro de l’autorisation européenne_ **unmapped**
* _Titulaire(s) : S’il y a plusieurs titulaires, les valeurs seront séparées par des « ; »_ **unmapped**
* _Surveillance renforcée (triangle noir) : valeurs « Oui » ou « Non »_ **unmapped**

### CIS_CIP_bdpm.txt 

Contains presentations infos.
Unfortunatly, french presentations are associated with medicines, which spanish presentation aren't.

* _Code CIS_ **unmapped**
* _Code CIP7 (Code Identifiant de Présentation à 7 chiffres)_ **unmapped**
* _Libellé de la présentation_ mapped to `PresentationForm#name`
* _Statut administratif de la présentation_ **unmapped**
* _Etat de commercialisation de la présentation tel que déclaré par le titulaire de l'AMM_ **unmapped**
* _Date de la déclaration de commercialisation (format JJ/MM/AAAA)_ **unmapped**
* _Code CIP13 (Code Identifiant de Présentation à 13 chiffres)_ `PresentationForm#PresentationFormId`
* _Agrément aux collectivités ("oui", "non" ou « inconnu »)_ **unmapped**
* _Taux de remboursement (avec un séparateur « ; » entre chaque valeur quand il y en a plusieurs)_ **unmapped**
* _Prix du médicament en euro_ **unmapped**
* _Texte présentant les indications ouvrant droit au remboursement par l’assurance maladie s’il y a plusieurs taux de remboursement pour la même présentation_ **unmapped**

### CIS_COMPO_bdpm.txt 

* _Code CIS_ mapped to `PrescriptionActiveIngredient#PrescriptionCode`
* _Désignation de l'élément pharmaceutique_  **unmapped** (for now) it is a packaging description 
* _Code de la substance_ mapped to `ActiveIngredient#ActiveIngredientID` and `PrescriptionActiveIngredient#ActiveIngredientID`
* _Dénomination de la substance_  mapped to `ActiveIngredient#name`
* _Dosage de la substance_
* _Référence de ce dosage (exemple : "[pour] un comprimé")_
* _Nature du composant (principe actif : « SA » ou fraction thérapeutique : « ST »)_
* _Numéro permettant de lier, le cas échéant, substances actives et fractions thérapeutiques_

### CIS_HAS_SMR_bdpm.txt 

* _Code CIS_
* _Code de dossier HA_
* _Motif d’évaluation_
* _Date de l’avis de la Commission de la transparence (format AAAAMMJJ)_
* _Valeur du SMR_
* _Libellé du SM_

### CIS_HAS_ASMR_bdpm.txt 

* _Code CIS_
* _Code de dossier HAS_
* _Motif d’évaluation_
* _Date de l’avis de la Commission de la transparence (format AAAAMMJJ)_
* _Valeur de l’ASMR_
* _Libellé de l’ASMR_

### HAS_LiensPageCT_bdpm.txt 

* _Code de dossier HAS_
* _Lien vers les pages d’avis de la CT_

### CIS_GENER_bdpm.txt 

This mapping will be complex !

* _Identifiant du groupe générique_ mapped to `HomogeneousGroup#HomogeneousGroupID`
* _Libellé du groupe générique_ mapped to `HomogeneousGroup#Name`
* _Code CIS_ the prescription having this name will have its `homogenousGroup` set to this identifier
* _Type de générique, avec les valeurs suivantes_ when this value is set to 0, the prescription will have its generic field set to true : 
** 0 : « princeps » 
** 1 : « générique » 
** 2 : « génériques par complémentarité posologique » 
** 4 : « générique substituable » 
* _Numéro permettant de trier les éléments d’un groupe_

### CIS_CPD_bdpm.txt 

* _Code CIS_
* _Condition de prescription ou de délivrance_

### CIS_InfoImportantes_AAAAMMJJhhmiss_bdpm.txt 

* _Code CIS_
* _Date de début de l’information de sécurité (format JJ/MM/AAAA)_
* _Date de fin de l’information de sécurité (format JJ/MM/AAAA)_
* _Texte à afficher et lien vers l’information de sécurité_

## Built With

## Contributing

Please read [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.

## Versioning

We use [SemVer](http://semver.org/) for versioning. For the versions available, see the [tags on this repository](https://github.com/your/project/tags). 

## Authors

* **Nicolas Delsaux** - *Initial work*

See also the list of [contributors](https://github.com/your/project/contributors) who participated in this project.

## License

This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details

## Acknowledgments

* Thanks to https://github.com/citiususc/calendula[Calendula] team. This tool is awesome !
* Obviously, what would I have done without Groovy ?
